package handlers;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_TASK_CREATE,
    POST_TASK_UPDATE_BY_ID,
    DELETE_TASK_BY_ID,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_SUBTASK_CREATE,
    POST_SUBTASK_UPDATE_BY_ID,
    DELETE_SUBTASK_BY_ID,
    GET_EPICS,
    GET_EPIC_BY_ID,
    GET_EPIC_SUBTASKS_BY_ID,
    POST_EPIC_CREATE,
    DELETE_EPIC_BY_ID,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS
}
